language: python

python:
- 2.7

install:
- sudo apt-get install postgis 
- sudo -u postgres createdb -E UTF8 -T template0 template_postgis
- sudo -u postgres psql -d template_postgis -c "CREATE EXTENSION postgis;"
- sudo -u postgres createdb -E UTF8 -T template_postgis lux
- sudo -u postgres createuser www-data --no-superuser --no-createdb --no-createrole
- sudo -u postgres psql -d lux -c 'CREATE SCHEMA geov3;'
- sudo -u postgres psql -d lux -c 'CREATE SCHEMA geov3_static;'
- sudo -u postgres psql -d lux -c "ALTER USER \"www-data\" PASSWORD 'www-data';"
- sudo -u postgres psql -d lux -c 'GRANT SELECT ON spatial_ref_sys TO "www-data";'
- sudo -u postgres psql -d lux -c 'GRANT ALL ON SCHEMA geov3 TO "www-data";'
- sudo -u postgres psql -d lux -c 'GRANT ALL ON SCHEMA geov3_static TO "www-data";'
- sudo -u postgres psql -d lux -c 'GRANT ALL ON geometry_columns TO "www-data";'

- make -f travis.mk .build/eggs.timestamp alembic.ini lux_alembic.ini
- .build/venv/bin/alembic upgrade head 
- .build/venv/bin/alembic -c lux_alembic.ini upgrade head 
- make -f travis.mk build

script:
- make -f travis.mk checks
