pdfConfig: !pdfConfig
  compressed: false
  author: "Jeff Konnen"
  subject: "geoportailv3 print templates"
  creator: "Mapfish Print"

throwErrorOnExtraParameters: true

templates:
  A4 portrait: !template
    pdfConfig: !pdfConfig
      title: "a4_portrait"
      keywords: ["legend", "map","validated"]
    reportTemplate: a4_portrait.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 470
        height: 650
      legend: !legend {}
      scalebar: !scalebar
        width: 150
        height: 30
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A4 landscape: !template
    pdfConfig: !pdfConfig
      title: "a4_landscape"
      keywords: ["legend", "map","validated"]
    reportTemplate: a4_landscape.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 715
        height: 395
      legend: !legend {}
      scalebar: !scalebar
        width: 150
        height: 30
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A3 portrait: !template
    pdfConfig: !pdfConfig
      title: "a3_portrait"
      keywords: ["legend", "map","validated"]
    reportTemplate: a3_portrait.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 715
        height: 975
      legend: !legend {}
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A3 landscape: !template
    pdfConfig: !pdfConfig
      title: "a3_landscape"
      keywords: ["legend", "map"]
    reportTemplate: a3_landscape.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 1064
        height: 640
      legend: !legend {}
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A2 portrait: !template
    pdfConfig: !pdfConfig
      title: "a2_portrait"
      keywords: ["legend", "map","validated"]
    reportTemplate: a2_portrait.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 1064
        height: 1475
      legend: !legend {}
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A2 landscape: !template
    pdfConfig: !pdfConfig
      title: "a2_landscape"
      keywords: ["legend", "map","validated"]
    reportTemplate: a2_landscape.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 1558
        height: 985
      legend: !legend {}
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A1 portrait: !template
    pdfConfig: !pdfConfig
      title: "a1_portrait"
      keywords: ["legend", "map","validated"]
    reportTemplate: a1_portrait.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 1558
        height: 2175
      legend: !legend {}
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A1 landscape: !template
    pdfConfig: !pdfConfig
      title: "a1_landscape"
      keywords: ["legend", "map","validated"]
    reportTemplate: a1_landscape.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 2255
        height: 1482
      legend: !legend {}
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A0 portrait: !template
    pdfConfig: !pdfConfig
      title: "a0_portrait"
      keywords: ["legend", "map","validated"]
    reportTemplate: a0_portrait.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 2254
        height: 3155
      legend: !legend {}
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
  A0 landscape: !template
    pdfConfig: !pdfConfig
      title: "a0_landscape"
      keywords: ["legend", "map","validated"]
    reportTemplate: a0_landscape.jrxml
    attributes:
      name: !string {}
      description: !string {}
      scale: !string {}
      url: !string {}
      qrimage: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 91, 128, 254, 300, 400]
        width: 3241
        height: 2173
      legend: !legend {}
      scalebar: !scalebar
        width: 230
        height: 40
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: mapSubReport}
    - !createScalebar {}
    - !prepareLegend # create a datasource for the report with the 'legend' attribute
      template: legend.jrxml
      inputMapper: {legend: legend}
      outputMapper:
        legend: legend
        legendSubReport: legendSubReport
        numberOfLegendRows: numberOfLegendRows
